import{a as P,S as q,i as c}from"./assets/vendor-Dy2ZTtfi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const B="51388045-e31683e898f5abc4ca9ab64e0",E="https://pixabay.com/api/",M=15;async function m(r,t=1){const s={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:t};return(await P.get(E,{params:s})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more");let R=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:i,comments:b,downloads:v})=>`
        <li class="gallery-item">
          <a href="${a}">
            <img src="${s}" alt="${e}" />
          </a>
          <div class="info">
            <p>Likes: ${o}</p>
            <p>Views: ${i}</p>
            <p>Comments: ${b}</p>
            <p>Downloads: ${v}</p>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){f.innerHTML=""}function L(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}function w(){g.classList.remove("hidden")}function u(){g.classList.add("hidden")}const S=document.querySelector(".form"),O=S.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");let l="",n=1,p=0;S.addEventListener("submit",async r=>{if(r.preventDefault(),l=O.value.trim(),n=1,!l){c.warning({message:"Please enter a search term!",position:"topRight"});return}$(),u(),L();try{const t=await m(l,n);if(d(),t.hits.length===0){c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),p=Math.ceil(t.totalHits/15),n<p&&w()}catch(t){d(),c.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}});x.addEventListener("click",async()=>{n+=1,L(),u();try{const r=await m(l,n);d(),y(r.hits),A(),n>=p?(c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),u()):w()}catch(r){d(),c.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(r)}});function A(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
